### ISSUE TITLE
eth_call support

### ISSUE THREAD

**Issue by i-norden** [vulcanize/ipld-eth-server#10]
ethdb.Database is in the ipld-eth-server backend from ipfs-ethdb: https://github.com/vulcanize/ipld-eth-server/blob/master/pkg/eth/backend.go#L46

1. Use that to create state.Database: https://github.com/vulcanize/go-ethereum/blob/master/core/state/database.go#L109

2. Use that to create state.StateDB: https://github.com/vulcanize/go-ethereum/blob/master/core/state/statedb.go#L119

3. Use that create an EVM: https://github.com/vulcanize/go-ethereum/blob/master/core/vm/evm.go#L139

4. Use that to reproduce DoCall: https://github.com/vulcanize/go-ethereum/blob/master/internal/ethapi/api.go#L817 in ipld-eth-server pkg/eth/backend.go

5. Use that to reproduce https://github.com/vulcanize/go-ethereum/blob/master/internal/ethapi/api.go#L930 in ipld-eth-server pkg/eth/api.go

NOTE: This will need to be optimized later on for Postgres, but should provide a quick route to support by using the geth types that already exist

**Comment by ramilexe** [comment]
https://github.com/vulcanize/eth-contract-watcher/issues/24

**Comment by i-norden** [comment]
Satisfied in #11
