### ISSUE TITLE
Support Parity tracing

### ISSUE THREAD

**Issue by i-norden** [vulcanize/ipld-eth-server#12]
https://openethereum.github.io/wiki/JSONRPC-trace-module#trace_call

https://openethereum.github.io/wiki/JSONRPC-trace-module#trace_callmany

Also note: https://github.com/ledgerwatch/turbo-geth/issues/1119#issuecomment-699028019

**Comment by i-norden** [comment]
@ramilexe can we close this from your tracing api work or is that different?

**Comment by AFDudley** [comment]
Tracing-api is the same issue.
