### ISSUE TITLE
Rebase to v1.10.18 versions of vdb geth 

### ISSUE THREAD

**Issue by i-norden** [vulcanize/ipld-eth-server#158]
Child of https://github.com/vulcanize/go-ethereum/issues/231

- [x] v3 release that uses the new v1.10.18-statediff-3.2.1 release of vdb geth (off of https://github.com/vulcanize/ipld-eth-server/tree/release-v3.2.0)
- [x] v4 release that uses the new v1.10.18-statediff-4.0.1-alpha release of vdb geth (off of https://github.com/vulcanize/ipld-eth-server/tree/release-v4.0.1-alpha)

This will also involve updating the dependency on ipfs-ethdb to use the releases resultant from: https://github.com/vulcanize/ipfs-ethdb/issues/34

**Comment by abdulrabbani00** [comment]
Final:

* v3 - 
* v4 -

**Comment by abdulrabbani00** [comment]
Need to make minor changes to fix deployment on tags.
