### ISSUE TITLE
go-ethereum v1.10.21 API updates

### ISSUE THREAD

**Issue by i-norden** [vulcanize/ipld-eth-server#177]
- [x] Update ChainID() API endpoint: https://github.com/ethereum/go-ethereum/pull/25166
- [x] Update tx returning API endpoints: https://github.com/ethereum/go-ethereum/pull/25155

**Comment by i-norden** [comment]
[This](https://github.com/vulcanize/ipld-eth-server/blob/ba01123f54e5d8fe99b98d26fa78f8d5b3e0d433/pkg/eth/backend_utils.go#L168) needs to be updated with the same new switch clause here: https://github.com/ethereum/go-ethereum/pull/25155/files

**Comment by i-norden** [comment]
And our ChainID endpoint https://github.com/vulcanize/ipld-eth-server/blob/ba01123f54e5d8fe99b98d26fa78f8d5b3e0d433/pkg/eth/api.go#L204 needs to be updated like https://github.com/ethereum/go-ethereum/pull/25166/files

**Comment by ABastionOfSanity** [comment]
Comments in the 1.10.21 geth release imply this is broken/incorrect in 1.10.20.  Revisiting for workalike behavior in our API.

**Comment by i-norden** [comment]
@ABastionOfSanity is this resolved? I see the fixed https://github.com/ethereum/go-ethereum/pull/25244 change is in, but it looks like https://github.com/ethereum/go-ethereum/pull/25166 didn't make it.
