### ISSUE TITLE
CHT support

### ISSUE THREAD

**Issue by ashwinphatak** [vulcanize/ipld-eth-server#179]
TBD: Figure out how this should be exposed (e.g. API details)

**Comment by i-norden** [comment]
Related: https://github.com/vulcanize/issue_tracking/issues/17

**Comment by AFDudley** [comment]
This will only apply to historic blocks so we should be able to build a watcher specifically for this data if anyone asks for it. I suspect no one will ever ask for it. So I'm closing the issue won't fix.
