### ISSUE TITLE
Ensure integration tests are running with the right version of go-ethereum

### ISSUE THREAD

**Issue by i-norden** [vulcanize/ipld-eth-server#184]
I am sure this is already implicitly covered by the ongoing CI/CD improvements but adding an issue for tracking purposes. For the integration tests in this repository where we check the results returned by our API vs the results returned from a go-ethereum client, we need to ensure we are using the right version of geth for these tests. This may currently be the case, but because of the number of degrees of indirection added to the CI due to stack_orchestrator it is very difficult to tell...

**Comment by AFDudley** [comment]
Superseded by https://github.com/cerc-io/stack-orchestrator
