### ISSUE TITLE
`eth_getBlockByNumber` and `eth_getBlockByHash` calls time out

### ISSUE THREAD

**Issue by prathamesh0** [vulcanize/ipld-eth-server#186]
In the current `getBlockByNumber` (and `getBlockByHash`) [implementation](https://github.com/vulcanize/ipld-eth-server/blob/release-v4.1.4-alpha/pkg/eth/backend.go#L285), the required objects are fetched in two steps:
* CIDs for required objects (header, uncles, transactions and receipts) are fetched from the index tables
* Corresponding IPLDs are fetched using individual queries in a loop

As a result, too many queries are fired (scaled by number of uncles / transactions) and the API call eventually times out if number of transactions in the block is high.

**Comment by AFDudley** [comment]
This kinda doesn't sound like a bug to me and/or a reason to work on `eth-watcher`? Is the suggestion that a proper stored procedure be used to batch the IPLD retrieval?

**Comment by prathamesh0** [comment]
> Is the suggestion that a proper stored procedure be used to batch the IPLD retrieval?

We can fire a single query (which uses join) each to fetch uncles, transactions and receipts and avoid firing queries in a loop.
