### ISSUE TITLE
GQL and getBlock API performance improvements

### ISSUE THREAD

**Issue by prathamesh0** [vulcanize/ipld-eth-server#202]
- The tables in the core database (TimescaleDB) are partitioned into chunks by `block_number`
- Add `block_number` to the filter in queries to improve performance of:
  - GQL APIs
  - `eth_getBlockByNumber` and `eth_getBlockByHash` APIs

**Comment by i-norden** [comment]
This looks like it was closed in https://github.com/cerc-io/ipld-eth-server/pull/201, please reopen if that is not the case.
