### ISSUE TITLE
Unit tests in CI failing with error `lost connection`

### ISSUE THREAD

**Issue by prathamesh0** [vulcanize/ipld-eth-server#203]
First noticed in https://github.com/cerc-io/ipld-eth-server/pull/201
The unit tests are run on a test machine and it's failing while attempting to SCP some files to it:
![image](https://user-images.githubusercontent.com/42446521/199719200-a100217a-4af6-49d7-b3fb-ef4d8ea5a124.png)
The tests pass locally.
@ABastionOfSanity Can you take a look?

**Comment by ABastionOfSanity** [comment]
I have reverted the minor change made in the workflow, and it still does not complete.  It is unclear if this is network problem or not.  Investigating with @srwadleigh

**Comment by ABastionOfSanity** [comment]
The target VM of the scp was  turned off.  It is now on again:
https://github.com/cerc-io/ipld-eth-server/actions/runs/3386884371/jobs/5631013221
