### ISSUE TITLE
Add support for post-London-hardfork endpoints

### ISSUE THREAD

**Issue by i-norden** [vulcanize/ipld-eth-server#213]
- [ ] eth_createAccessList
- [ ] eth_feeHistory (https://github.com/ethereum/go-ethereum/blob/master/internal/ethapi/api.go#L90)
- [ ] eth_estimateGas
- [ ] eth_gasPrice
- [ ] eth_maxPriorityFeePerGas

**Comment by i-norden** [comment]
Do fall through support to proxy geth node first

**Comment by AFDudley** [comment]
The goal is to support helios
https://github.com/a16z/helios
https://a16zcrypto.com/building-helios-ethereum-light-client/

**Comment by rickmanelius** [comment]
Noting this ticket was referenced in the customer pipeline review this morning. To clarify, this work is needed in order to close out the deal with Liam, Infura, or both? cc @erikdies

**Comment by erikdies** [comment]
@rickmanelius Both I believe, this is rounding out the offering.

**Comment by AFDudley** [comment]
Ultimately, I expect it's for both, but we shouldn't use client names in public repos.

**Comment by rickmanelius** [comment]
My mistake. Will not post that in any public/private repos going forward.

**Comment by AFDudley** [comment]
@i-norden Please close if completed.

**Comment by i-norden** [comment]
@AFDudley hasn't been completed, but not sure if we still want/need to do this. Watchers do not use these endpoints, this task was related to using ipld-eth-server as a general geth RPC replacement back when we were toying with the RPC as a service ideas
