### ISSUE TITLE
update `eth_writeStateDiffAt` behavior

### ISSUE THREAD

**Issue by i-norden** [vulcanize/ipld-eth-server#226]
Sister issue of https://github.com/cerc-io/go-ethereum/issues/296

Make the changes to be compatible with the new endpoint from https://github.com/cerc-io/go-ethereum/pull/306

Expected behavior:
1. Initial query comes in
2. Cant satisfy it locally
3. Get result from remote node
4. Tell remote node to statediff missing data
5. Return the result from the remote node (without waiting for result from 4)

**Comment by roysc** [comment]
No changes should be needed for this, as the function signature of the endpoint method hasn't changed and the returned job status is not used.
