### ISSUE TITLE
GraphQL endpoints should be forwardable to proxy nodes

### ISSUE THREAD

**Issue by i-norden** [vulcanize/ipld-eth-server#239]
Right now the GraphQL backend calls directly into the "eth" backend, skipping over the "eth" API abstraction where the forwardOnError and forwardEthCall/forwardStorageAt functionality is enabled.

**Comment by AFDudley** [comment]
How is this possible? How are the watchers actually working then? Seems like this an issue with ETH watcher not existing and maybe this feature should just be moved over there? @dboreham

**Comment by dboreham** [comment]
It would mean that the requests are being processed successfully in ipld-eth-server, so no forward-on-error is needed.

In general forward on error is a bit of an antipattern. The ability to forward a particular configured workload is useful, but forwarding when something fails is problematic for a number of reasons, outside of dev testing scenarios.

**Comment by telackey** [comment]
https://git.vdb.to/cerc-io/ipld-eth-server/issues/239
