### ISSUE TITLE
Test improvements

### ISSUE THREAD

**Issue by i-norden** [vulcanize/ipld-eth-server#244]
* The integration tests that compare geth results to results returned by ipld-eth-server should compare the "raw" JSON returned from the endpoints, rather than first unpacking this JSON into Go types. This is because the Go types sometimes only represent a subset of the data returned in the JSON payload, see comments on.
* API unit tests should test under different chainconfig (tx signer) conditions,
* Tests should cover all tx types: https://github.com/cerc-io/ipld-eth-server/issues/243
* getLogs tests should cover more filter conditions, including a block range test

See comments on https://github.com/cerc-io/ipld-eth-server/pull/242

**Comment by telackey** [comment]
https://git.vdb.to/cerc-io/ipld-eth-server/issues/244
