### ISSUE TITLE
eth_getCode returns error

### ISSUE THREAD

**Issue by ramilexe** [vulcanize/ipld-eth-server#57]
eth_getCode returns error when block number set to `nil`:

`ipldClient.CodeAt(ctx, common.HexToAddress(contractAddress), nil)`

Return message:

```
{
      Code: -32000,
      Message: "sql: converting argument $1 type: uint64 values with high bit set are not supported",
      Data: nil,
}
```

**Comment by i-norden** [comment]
What happens if you send `nil` to geth?

**Comment by i-norden** [comment]
You'll get an error of the form: `errors.New("invalid arguments; neither block nor hash specified")`, so it should be returning an error.

**Comment by i-norden** [comment]
Also the arg is `rpc.BlockNumberOrHash`

**Comment by ramilexe** [comment]
> What happens if you send `nil` to geth?

It returns code without any errors

**Comment by i-norden** [comment]
That doesn't seem right.

https://github.com/vulcanize/go-ethereum/blob/master/internal/ethapi/api.go#L729 => https://github.com/vulcanize/go-ethereum/blob/f26c19cbcd60175598824c7e09b64b8896daf721/eth/api_backend.go#L171

**Comment by ramilexe** [comment]
>That doesn't seem right.
It is right.

https://github.com/vulcanize/ipld-eth-server/pull/53/files#diff-8118e44ac15fb5ab2e2ece2ab52fd23062a10b5cc9c55ee5b3620a1242cff27cR186-R194 

![image](https://user-images.githubusercontent.com/1008882/115250787-937fe000-a132-11eb-9108-cd42f3b8a543.png)

**Comment by i-norden** [comment]
Thanks! I think the RPC server must be converting the `nil` arg to `rpc.LatestBlockNumber` (-1)  behind the scenes, which is causing the issue.

**Comment by ramilexe** [comment]
Fixed in commit https://github.com/vulcanize/ipld-eth-server/pull/53/commits/9b960a105fe7fe38cfe584bba2b5b324de22f3d3
