### ISSUE TITLE
Integration test plan

### ISSUE THREAD

**Issue by ramilexe** [vulcanize/ipld-eth-server#67]
### Deploy contract, send eth:

- [x] get block 
- [x] get tx
- [x] get receipt
- [x] filter logs
- [x] get code at
- [x] get balance
- [x] get storage
- [x] eth call

The same with gap filling

### ERC20 transfer:

- [] get block 
- [] get tx
- [] get receipt
- [] filter logs
- [] get code at
- [] get balance
- [] get storage
- [] eth call

### Destroy contract:

- [] get block 
- [] get tx
- [] get receipt
- [] filter logs
- [] get code at
- [] get balance
- [] get storage
- [] eth call

**Comment by arijitAD** [comment]
Merged https://github.com/vulcanize/ipld-eth-server/pull/53 
We need to add tests for the ERC20 transfer and Destroy contract

**Comment by arijitAD** [comment]
Move this to smaller issues #74 and #75
