### ISSUE TITLE
GQL API for getStorageAt and getLogs

### ISSUE THREAD

**Issue by ashwinphatak** [vulcanize/ipld-eth-server#68]
Enhance the GQL API to support:

* getStorageAt - return leaf node value given (block hash, contract address, storage slot)
* getLogs - return receipt/logs given (block hash, contract address)

**Comment by ashwinphatak** [comment]
TODO

* Update code for same semantics as in the integration test PR/code changes
* Add integration test for GQL `getStorageAt` and `getLogs`

**Comment by arijitAD** [comment]
Added tests https://github.com/vulcanize/ipld-eth-server/pull/69 
The integration test is failing in CI. We can merge this. Once https://github.com/vulcanize/ipld-eth-server/pull/53 is merged to master we can fix the failing test.
