### ISSUE TITLE
Add log index in the log table.

### ISSUE THREAD

**Issue by arijitAD** [vulcanize/ipld-eth-server#70]
`GetLogs` RPC returns the filtered logs. We need to store the Log index in DB in order to optimize the RPC.
Currently, We fetch all the logs from the DB between two blocks and then filter them based on request.

We need to implement this first:
https://github.com/vulcanize/go-ethereum/issues/79

**Comment by i-norden** [comment]
Closed in https://github.com/vulcanize/ipld-eth-server/pull/92
