### ISSUE TITLE
Update ipfs-ethdb dependency

### ISSUE THREAD

**Issue by stellarmagnet** [vulcanize/ipld-eth-server#86]
Currently `ipld-eth-server` is dependent on the [v0.0.2-alpha](https://github.com/vulcanize/ipfs-ethdb/tree/v0.0.2-alpha) release of `ipfs-ethdb` - but this is an old version of the code. 

We need to update the dependency to this release:
https://github.com/vulcanize/ipfs-ethdb/tree/v0.0.2

**Comment by i-norden** [comment]
#91 will perform this

**Comment by i-norden** [comment]
Closed in https://github.com/vulcanize/ipld-eth-server/pull/91
